In [1]:
import numpy as np

**NumPy is a scientific computing package (library) for python programming language. 
Num stands for numerical and Py stands for Python programming language.Python NumPy library is especially used for numeric and mathematical calculation like linear algebra, Fourier transform, and random number capabilities using Numpy array.
special advantage over Python list is given below.

1.Faster
2.Uses less memory to store data.
3.Convenient. **

**To use NumPy first import it. For import NumPy, follows below syntax in the python program file
import numpy as np

import: import keyword imports the NumPy package in the current file.

as:  as is a keyword used to create sort name of NumPy.

np: np is a short name given to NumPy, you can give any name (identifier) instead of it. If we use NumPy name in the program repeatedly so it will consume typing time and energy as well so for that we gave a short name for our convenience.
**

**Create one dimesion array**

In [2]:
x=np.array([1,4,3,5,6])
x.argsort()


array([0, 2, 1, 3, 4], dtype=int32)

**Create two dimension array**

In [3]:
y=np.array([[1,2,3],[9,8,7],[22,33,11]])
y

array([[ 1,  2,  3],
       [ 9,  8,  7],
       [22, 33, 11]])

**Create Three Dimesion Array**

In [4]:
z=np.array([[[1,2,3],[3,4,5]]])
z

array([[[1, 2, 3],
        [3, 4, 5]]])

**How to check the type of ndarray?
The type() function give the type of data.**

In [5]:
type(y)

numpy.ndarray

**How to check dimension of NumPy ndarray?
The ndim attribute help to find the dimension of any NumPy array.**

In [6]:
y.ndim

2

**How to check the size of the NumPy array?
The size attribute help to know, how many items present in a ndarray.
9 value represent, total 9 item present in the 2D array x.**

In [7]:
y.size

9

**The shape attribute help to know the shape of NumPy ndarray. It gives output in the form of a tuple data type. Tuple represents the number of rows and columns. Ex: (rows, columns)**

In [8]:
y.shape

(3, 3)

**How to check the data type of NumPy ndarray?
The dtype attribute help to know the data type of ndarray.
as per the below output 'y' contain integer type data. This data store in 32 bit format (4 byte).**

In [9]:
y.dtype

dtype('int32')

**Create metrics using python NumPy functions 
Ones metrics use NumPy ones() function.**

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**if you want to change data type then use dtype=int as parameter**

In [11]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

**Zeros metrics use NumPy zeros() function**

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Empty metrics use NumPy empty() function. 
By default NumPy empty() function give float64 bit random value. According to your requirement change dtype.**

In [14]:
np.empty((2,2))

array([[9.76118065e-313, 2.22809558e-312],
       [2.14321575e-312, 6.23059386e-307]])

# Some useful function

**Create NumPy 1D array using arange() function**

In [15]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Create NumPy 1D array using linspace() function

Return evenly spaced numbers over a specified interval**

In [16]:
x=np.linspace(1,5,4)
x

array([1.        , 2.33333333, 3.66666667, 5.        ])

**Convert 1D array to multidimensional array using reshape() function**

In [17]:
x=np.arange(1,13)#1 D Array
new_x=np.reshape(x, (3,4))
new_x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
x_reshape=np.arange(1,13).reshape(3,4)
x_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Convert multidimensional array in one dimensional

To convert multidimensional array into 1D use ravel() or flatten() function.**

In [19]:
x_reshape.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
x_reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Transpose metrics--row to column and column to row**

In [21]:
x=np.arange(1,13).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Numpy Mathematica Functions

**NumPy Arithmetic Operations
Using Python NumPy functions or operators solve arithmetic operations.**

In [23]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,10).reshape(3,3)
 
# print arr1 and arr2
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Addition of Two Numpy Array
Using + Operator**

In [24]:
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
np.add(x,y)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Subtraction of Two NumPy Array**

In [26]:
x-y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.subtract(x,y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Division of Two NumPy Array**

In [28]:
x/y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.divide(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Multiplication of Two NumPy Array**

In [30]:
x*y

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [31]:
np.multiply(x,y)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Matrix Product of Two NumPy Array (matrix)
--"using @ Operator"
--"Using np.dot() function"**

In [32]:
x@y

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [33]:
np.dot(x,y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])