# NumPy Mathematical Built-in functions

In [1]:
import numpy as np

In [2]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**np.max()**

*To find maximum value from an array.*

In [3]:
x.max()

9

In [4]:
x.max(axis=1)    # return max value from each row

array([3, 6, 9])

In [5]:
x.max(axis=0)    # return max value from each column

array([7, 8, 9])

**nparray.argmax()**

*it will give the index number of the maximum valu e.g. in our case 9 is the maximum value in the 2D array and you can check it is at index number 8 so output will be 8*

In [6]:
x.argmax()

8

In [7]:
y=np.array([[1,2,3],[99,44,55],[101,22,11]])
y

array([[  1,   2,   3],
       [ 99,  44,  55],
       [101,  22,  11]])

In [8]:
y.max()# in this 2D array 101 is maximum value

101

In [9]:
y.argmax()   #And 101 is at index number 6

6

**nparray.min()**

*To find minimum value from an array.*

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x.min()

1

In [12]:
x.min(axis=1)  # return max value from each row

array([1, 4, 7])

In [13]:
x.min(axis=0)   # return max value from each column

array([1, 2, 3])

**nparray.argmin()**

*it will give the index number of the minimum valu e.g. in our case 1 is the minimum value in the 2D array and you can check it is at index number 0 so output will be 0*

In [14]:
x.argmin()

0

**nparray.sum()**

*Return sumation of NuPy array.*

In [15]:
x.sum()      # you can also use np.sum(x)  

45

In [16]:
x.sum(axis=1)
# you can also try np.sum(x,axis=1)

array([ 6, 15, 24])

In [17]:
x.sum(axis=0)

array([12, 15, 18])

**np.mean()**

*Return mean of NumPy array.*

In [18]:
np.mean(x)

5.0

**np.sqrt()**

*Return square root of each element of NumPy array.*

In [19]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

**np.std()**

*Return standerd division of Numpy array.*

In [20]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

**no.exp()**

*Return exponential value of each element of the NumPy array.*

In [21]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

**no.log()**

*Return natural log of each element of NumPy array.*

In [22]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

**np.log10()**

*Return log to the base 10 value of each element of NumPy array.*

In [23]:
np.log10(x)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

**nparray.argsort()**

*it will give the index value which tell us that all the element should be sort in this mannar, Rememeber it never give you sorted elements*

In [24]:
y

array([[  1,   2,   3],
       [ 99,  44,  55],
       [101,  22,  11]])

In [25]:
y.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]], dtype=int32)

**understand the above and below code both are same because default argsort take axis=1 means row wise. Here in the first row minimum value is 1 then 2 will come than 3 will come if are talking about the sorting of elements that's why index value is coming[0,1,2] , in the second row 44 will come first than 55 than 99 so index value[1,2,0] is appearing and same proceduer for row 3rd.** 

In [26]:
y.argsort(axis=1)  # give sorted element index row wise

array([[0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]], dtype=int32)

In [27]:
y.argsort(axis=0)   # give sorted element index column wise

array([[0, 0, 0],
       [1, 2, 2],
       [2, 1, 1]], dtype=int32)

In [28]:
#let's understand it with the 1D array
z=np.array([2,9,1,7,8])
z

array([2, 9, 1, 7, 8])

In [29]:
z.argsort()# here index 2 menas elment value 1 comes first place then
           #index 0 means element value 2 will come at second palce
           #index 3 means element value 7 will come at 3rd palce
           #index 4 means element value 8 will come at 4th palce
           #index 1 means element value 9 will come at 5th palce

array([2, 0, 3, 4, 1], dtype=int32)

# Slicing in Numpy Array

In [30]:
x=np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

**if you want some specific rows and some specific columns as per your requirement then you can use slicing.You have some idea of slicing in list(in python).**

**so let's start with slicing in numpy array , the syntax is like nparray.[ : , : ].**

***in this there are two : shown so first : is used for rows slicing and second : is used for column slicing we will understand first row slicing then column slicing then both.***

In [31]:
x[0,2]# if you are not using ":" then it will give value at ith row and jth column

3

In [32]:
x[0:]# if you need start from index 0 to all rows and all colmns

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [33]:
x[2:]# means start row indexing from 2 to all rows and all colmns

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [34]:
x[4:]# means start row indexing from 4 to all rows and all colmns

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [35]:
x[2:4]# means start row indexing from 2 to index 3 rows only

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [36]:
x[1:7]# means start row indexing from 1 to index 6 rows only and all colmns

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [37]:
x[:,1:]# means start column indexing 1 to all colmns and all rows

array([[  2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
x[:,1:4]# means start column indexing 1 to  columns indexing 3 and all rows

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [39]:
x[:,3:7]# means start column indexing 3 to  columns indexing 6 and all rows

array([[ 4,  5,  6,  7],
       [14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67],
       [74, 75, 76, 77],
       [84, 85, 86, 87],
       [94, 95, 96, 97]])

In [40]:
x[2:6,1:4]# means start index from 2 to 5th index rows And
          #start column indexing 1 to  columns indexing 3 

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

# Concatenate

**if you want to concatenate two or more numpy array then use concatenate().it take tuple as sequence**

In [41]:
x=np.arange(1,17).reshape(4,4)
y=np.arange(17,33).reshape(4,4)

In [42]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
y

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [44]:
np.concatenate((x,y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [45]:
#default value of axis is 0 menas if you want to concatenate numpy array horizontally
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [46]:
#if you take axis is 1 menas if you want to concatenate numpy array vertically
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

**you can use vstack() for vertically concatenation and hstack() for horizontally concatenation**

In [47]:
np.vstack((x,y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [48]:
np.hstack((x,y))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# spliting the numpy array

**if you want to your numpy array into parts then use split().**

**np.split(nparray,parts,axis)**

**But remember for example you are trying to split a 2D array then it will split in eqaul parts, if you provide a parameter value which is not split it into equal part then an error will be produce**

In [49]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
np.split(x,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [51]:
np.split(x,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [52]:
y=np.array([4,7,1,3,9,55,77])
y

array([ 4,  7,  1,  3,  9, 55, 77])

In [53]:
np.split(y,[3]) # it will split into two part because inn list you prove single value"3"
                #1st part is befor index 3 means index number[0,1,2]
                # 2nd part is from 3 index to end

[array([4, 7, 1]), array([ 3,  9, 55, 77])]

In [54]:
np.split(y,[2,4,5])# here four part will be formed because you given 3 values in list
                   # 1st split is before index 2 means index number [0,1]
                   # 2nd split is from index 2 and to index number 3 means index number [2,3]
                   # 3rd split is from index 4 and to index number 4 means index number [4]
                   # 4th split is from index 5 and to last index number means index number [5,6]

[array([4, 7]), array([1, 3]), array([9]), array([55, 77])]