In [1]:
import numpy as np

# Python NumPy random module

In [2]:
import random # import random module

**np.random.random()**

*This function generates float value between 0.0 to 1.0 and returns ndarray if you will give shape.*

In [5]:
x = np.random.random(1)
print(x)

[0.96317771]


In [6]:
y =  np.random.random((3,3))
print(y)

[[0.17902977 0.84583536 0.71878124]
 [0.67189622 0.16153655 0.55810622]
 [0.48766352 0.08423788 0.0411775 ]]


**np.random.randint()**

*The random integer function generates single random integer number from given range and if the shape will give then return ndarray.*

In [8]:
rd_no = np.random.randint(1,4)
print(rd_no)

1


In [10]:
rd_2D = np.random.randint(1,4, (4,4))
print(rd_2D)

[[3 1 3 1]
 [2 2 1 3]
 [2 3 2 3]
 [1 1 2 1]]


In [11]:
rd_3D = np.random.randint(1,4, (2,4,4))
print(rd_3D)

[[[3 2 1 2]
  [1 1 1 3]
  [2 2 3 2]
  [1 3 3 1]]

 [[3 1 3 2]
  [1 3 2 2]
  [3 2 3 2]
  [3 3 1 1]]]


**np.random.seed()**

*The random module generates random number but next time you want to generate the same number then seed() will help.*

In [12]:
np.random.seed(10)
rd_3D = np.random.randint(1,4, (2,4,4))
print(rd_3D)


[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


**Next time generate the same 3D array using the same seed value (10).**

*Note: The seed function accepts value up to  2^32 -1 (4294967295).*


In [13]:
np.random.seed(10)
rd_3D = np.random.randint(1,4, (2,4,4))
print(rd_3D)


[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


**np.random.rand()**

*The rand() function work like random() but it accept shape and return ndarray which contain random values between 0.0 to 1.0.*

In [14]:
arr_2D = np.random.rand(3,3) # return  3 x 3 matrix
print(arr_2D)


[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


**np.random.randn()**

*The randn() function work like rand() function but it return samples of  standerd normalise distribution value.(it will give negative values also)*

In [15]:
arr_2D = np.random.randn(3,3)
print(arr_2D)

[[ 0.67893119 -1.91355421 -0.94245806]
 [-1.74554298 -1.02094527 -0.16206903]
 [-0.6579709   0.42211306  0.62402334]]


**np.random.choice()**

*If you have sequence values and want to get random single value then the random choice() function is the best choice.*

In [16]:
x = [1,2,3,4] # list
choice_x = np.random.choice(x) # return random single item from sequence
print(choice_x )


1


*Let’s try to get the number of choice from sequence x using for loop.*

In [17]:
for i in range(20):
    print(np.random.choice(x))

1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4
1
1
1


**np.random.permutation()**

*If you want to generate some permutation of sequence then use random permutation() function.*

In [19]:
x=[1,2,3,4]
x1 = np.random.permutation(x)
print(x1)

[1 3 4 2]


# Python NumPy String Operations Methods

**If you want to work on string data then NumPy string operations methods help to do work easy. The python NumPy support a bunch of string operations, string comparison, and string information methods.**

In [24]:
x='learning ML is very good'
y='ML is very easy'

**np.char.add()**

*This function use to add two strings.*

In [25]:
z=np.char.add(x,y)
print(z)

learning ML is very goodML is very easy


In [27]:
# Or you can use
print(x+y)

learning ML is very goodML is very easy


**np.char.multiply()**

*This function helps to duplicate string required number of times.*

In [29]:
#Syntax: np.char.multiply(string_array, number)
z=np.char.multiply(x,2)
print(z)

learning ML is very goodlearning ML is very good


**np.char.capitalize()**

*The capitalize() function convert given string’s first character in capital format.*

In [30]:
print(np.char.capitalize(x))#only first character will be in capital letter

Learning ml is very good


**np.char.lower()**

*The lower() function convert given string in lower case..*

In [31]:
print(np.char.lower(x))#all charcter will convert into lower case

learning ml is very good


**np.char.upper()**

*The upper() function convert given string in upper case..*

In [33]:
print(np.char.upper(x))#all charcter will convert into upper case

LEARNING ML IS VERY GOOD


**np.char.title()**

*The title() function convert given string in title format..*

In [34]:
print(np.char.title(x))# all the first character will convert into captial letter

Learning Ml Is Very Good


**np.char.center()**

*The center() function set the string in the center of given string length. If you want to fill the string’s side blank space. Then give fillchar parameter with character.*

In [36]:
print(np.char.center(x,40))#you have to specify the width(in our case we use 40)

        learning ML is very good        


In [37]:
print(np.char.center(x,40,fillchar='*'))

********learning ML is very good********


**np.char.split()**

*The split() function split the string in a list of items. By default split function split the string by space.*

In [38]:
print(np.char.split(x))

['learning', 'ML', 'is', 'very', 'good']


**np.char.splitlines()**

*The splitlines() function split the string by lines in a list as elements.*

In [39]:
print(np.char.splitlines("I\nAm\nIndian")) # splitlines string


['I', 'Am', 'Indian']


In [40]:
print(np.char.splitlines(x))#here x is a single line so output will be as below

['learning ML is very good']


**np.char.join()**

*The join() function join the echa character of given sequence by seperator.*

In [43]:
print(np.char.join([":", "/"], [x,y]))

['l:e:a:r:n:i:n:g: :M:L: :i:s: :v:e:r:y: :g:o:o:d'
 'M/L/ /i/s/ /v/e/r/y/ /e/a/s/y']


In [44]:
print(np.char.join([":", "/"], ['vivek','kumar']))

['v:i:v:e:k' 'k/u/m/a/r']


**np.char.replace()**

*The replace() function replace existing string by new given string.*

In [46]:
print(np.char.replace(x, "learning", "Learn"))

Learn ML is very good


# Python NumPy String Comparison 
## The string comparison methods use to compare string with each other and return a boolean value.

**np.char.equal()**

*The equal() function return “True” boolean value, If both strings are same else “False”.(or use double equal to operator)*

In [47]:
str = np.char.equal(x,y) # check equality
print(str)

False


In [48]:
x==y

False

**np.char.not_equal()**

*The not_equal() function return “True” boolean value, If both strings are not same else “False”.*

In [49]:
str = np.char.not_equal(x,y) # check equality
print(str)

True


# Python NumPy string Information
## The string information methods use to get information from the stings.

**np.char.count()**

*The count() function count string from an existing string and return number.*

In [51]:
str1='hi indians say hi to india'
print(np.char.count(str1,'i'))

6


**np.char.find()**

*The find() function find given string from an existing string and return the index of the first character of that string*

In [54]:
print(np.char.find(str1,'i'))

1


In [58]:
print(np.char.find(str1,'zip'))

-1


**np.char.index()**

*The index() function find an index of a given string from an existing string and return the index of the first character of that string. If string will not found then return ValueError.*
**so this is the basic differnce between index() and find() if you are using find() and string does not exist then index will give -1 value but in the case of index it will give a value error.**

In [57]:
print(np.char.index(str1,'hi'))

0


In [60]:
#  try this
#print(np.char.index(str1,'zip'))

**np.char.isdecimal()**

*The isdecimal() function return “True”. If the string contains each and every character are decimal.*

In [61]:
print(np.char.isdecimal("Hello") )

False


**np.char.isdigit()**

*The isdigit() function return “True”. If the string contains each and every character are digits.*

In [62]:
print(np.char.isdigit("Hello") )

False


**np.char.islower()**

*The islower() function return “True”. If string contain each and every character in lowercase.*

In [63]:
print(np.char.islower("Hello") )

False


**np.char.isupper()**

*The isupper() function return “True”. If string contain each and every character in uppercase.*

In [64]:
print(np.char.isupper("Hello") )

False


**np.char.isnumeric()**

*The isnumeric() function return “True”. If string contain each and every character in numeric form.*

In [65]:
print(np.char.isnumeric("Hello") )

False


**np.char.isspace()**

*The isspace() function return “True”. If string contain blank space.*

In [72]:
print(np.char.isspace("Hello") )

False


In [74]:
print(np.char.isspace(" ") )

True
